language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  webhooks: https://www.travisbuddy.com/?insertMode=update
  on_success: never
  email: false
node_js:
  - '13'
  - '12'
  - '11'
  - '10'
script: "yarn run test-travis"
after_success:
  - codacy-coverage < lcov.info
  - semantic-release
  - yarn run changelog
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
