language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
script: "yarn run test-travis"
after_success:
  - codacy-coverage < lcov.info
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
