language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
script: "yarn run test-travis"
after_success:
  - codacy-coverage < lcov.info
  - yarn run semantic-release
  - yarn run changelog
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
